### ISSUE TITLE
[REQUEST] Thank you and Request for Translation.

### ISSUE THREAD

**Issue by kimjiwongit** [AoraMD/Pages#1]
https://github.com/AoraMD/Pages

I have visited the blog and I absolutely love the style of your tutorials. Would it be possible for you to provide English translation.

The blog is in Chinese language and I honestly want to share it with English speaking developers.

(I love Anime styled art btw)

And if you cannot translate, it does not matter. I am a huge fan. Please keep on writing the Blog regularly.

**Comment by AoraMD** [comment]
> https://github.com/AoraMD/Pages
> 
> I have visited the blog and I absolutely love the style of your tutorials. Would it be possible for you to provide English translation.
> 
> The blog is in Chinese language and I honestly want to share it with English speaking developers.
> 
> (I love Anime styled art btw)
> 
> And if you cannot translate, it does not matter. I am a huge fan. Please keep on writing the Blog regularly.

Thanks for your praises. Actually the blog's theme is based on an open source Jekyll theme called [Halve](https://github.com/TaylanTatli/Halve), and all illustrations are from [Pixiv](https://www.pixiv.net)(Just as a notebook, I never make profits through this blog.), everyone can build their own.

**Comment by kimjiwongit** [comment]
Yes. Can I know the roadmap or future of your blog?
I am excited for new contents.

**Comment by AoraMD** [comment]
This page will post articles related to mobile application development (mainly Android).
